N_VARIANTS: 50
NStartpoints: 10
Niterations: 1000
N_MCMC: 10000
N_SHUFFLE: 2
BURN_IN: 500
THINNING: 1
GEN_SEED: 42
ADNI_MCMC_SEED: 4790
JS: [50, 200, 500, 1000]
MCMC_SEED: 53
RS: [0.1, 0.25, 0.5, 0.75, 0.9]
N_BOOTSTRAP: 50
SA_EBM_ALGO_NAMES: ['conjugate_priors', 'mle', 'kde', 'em', 'hard_kmeans']
OTHER_ALGO_NAMES: ['debm', 'debm_gmm', 'ucl_gmm', 'ucl_kde']
OUTPUT_DIR: 'algo_results'
EXPERIMENT_NAMES:
  - sn_kjOrdinalDM_xnjNormal            # Experiment 1: Ordinal kj with Dirichlet-Multinomial, Normal Xnj
  - sn_kjOrdinalDM_xnjNonNormal         # Experiment 2: Ordinal kj with Dirichlet-Multinomial, Non-Normal Xnj
  - sn_kjOrdinalUniform_xnjNormal       # Experiment 3: Ordinal kj with Uniform distribution, Normal Xnj
  - sn_kjOrdinalUniform_xnjNonNormal    # Experiment 4: Ordinal kj with Uniform distribution, Non-Normal Xnj
  - sn_kjContinuousUniform              # Experiment 5: Continuous kj with Uniform distribution
  - sn_kjContinuousBeta                 # Experiment 6: Continuous kj with Beta distribution
  - xiNearNormal_kjContinuousUniform    # Experiment 7: Near-normal Xi with Continuous Uniform kj
  - xiNearNormal_kjContinuousBeta       # Experiment 8: Near-normal Xi with Continuous Beta kj
  - xiNearNormalWithNoise_kjContinuousBeta  # Experiment 9: Same as Exp 8 but with noises to xi